# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-remote-state-base"
    key            = "infra/./terraform.tfstate"
    region         = "ap-southeast-2"
    encrypt        = false
    dynamodb_table = "tf-remote-state-base"
  }
}
